version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: delivery
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"