services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql+aiomysql://root:${MYSQL_ROOT_PASSWORD}@$db:3306/${MYSQL_DATABASE}
      REDIS_URL: redis://redis:6379
  db:
    image: mysql:8.0
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
      
  redis:
    image: redis:6.2
    env_file:
      - .env
    ports:
      - "6379:6379"

volumes:
    db_data: